CREATE TABLE IF NOT EXISTS salary_adjustments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_tax_id VARCHAR(64) NOT NULL,
  employee_id INT NOT NULL,
  workdays_id INT DEFAULT NULL,
  month VARCHAR(7) NOT NULL, -- YYYY-MM
  items JSON,
  net_amount DECIMAL(12,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
